repos:
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox -e py39
        language: system
        types: [python]
        verbose: true
        pass_filenames: false
